MVI docs
surfstudio/surf-mvi-flow pull request #11
Opened 2022-02-10 08:23 UTC by ruslansharipov

For now I decided to add docs in Russian. In my opinion docs are have to be translated later when the library becomes stable (and by someone with stronger knowledge of the English language)

Closes #10

2022-02-18 08:07 UTC, margarita-v approved these changes
🔥

2022-02-18 08:07 UTC, margarita-v commented on docs/README.md
> +    Отвечает за изменение текущего состояния (и отправку сайд-эффектов, о них чуть позже). Каждый раз когда какое-то событие попадает оказывается в EventHub’е - оно прилетает в редьюсер, который долж
```suggestion
    Отвечает за изменение текущего состояния (и отправку сайд-эффектов, о них чуть позже). Каждый раз, когда какое-то событие оказывается в EventHub’е, оно прилетает в редьюсер, который должен решить, нужно ли как-то изменить состояние. Редьюсер, и только редьюсер, может менять состояние вью.
```

2022-02-18 08:07 UTC, margarita-v commented on docs/README.md
> +Если мы используем Android View Framework и просто подпишемся на Observable состояние экрана и будем каждый раз полностью его перерисовывать когда получим новое состояние - на экранах с большим колич
```suggestion
Если мы используем Android View Framework и просто подпишемся на Observable состояние экрана и будем каждый раз полностью его перерисовывать, когда получим новое состояние, то на экранах с большим количеством логики и сложными вью может упасть FPS. И чем чаще будет обновляться состояние, тем сильнее будет падение.
```

2022-02-18 08:07 UTC, margarita-v commented on docs/README.md
> +Для этого было сделано просто решение - перерисовывать только те части экрана, которые поменялись или отрисовываются в первый раз.
```suggestion
Для этого было сделано простое решение: перерисовывать только те части экрана, которые поменялись или отрисовываются в первый раз.
```

2022-02-18 08:07 UTC, margarita-v commented on docs/README.md
> +Но уже очень скоро на всех проектах студии будет использоваться Compose и дополнительные действия не потребуются, так как в Compose подсчет Diff есть из коробки и Compose отлично подходит под работу
```suggestion
При использовании Jetpack Compose дополнительные действия не потребуются, так как в Compose подсчет Diff есть из коробки и Compose отлично подходит под работу с единым состоянием.
```

2022-02-18 08:07 UTC, margarita-v commented on docs/README.md
> +## Roadmap
I suggest to remove it and to keep such ideas in issues (some of them are added)

2022-02-18 08:07 UTC, margarita-v commented on docs/README.md
> +- С запросом в сеть и обработкой ошибок с помощью ErrorHandler (используется на большинстве проектов студии).
```suggestion
- С запросом в сеть и обработкой ошибок с помощью ErrorHandler (используется на большинстве проектов).
```
we are growing, so we are a company now :)

2022-02-18 11:15 UTC, dmitry-kuzmenchuk requested changes

2022-02-18 11:15 UTC, dmitry-kuzmenchuk commented on docs/DSL.md
> +1. **mapTo** - трансформация события в событие. Используется, когда например событие клика по кнопке нужно трансформировать в событие открытие диалога.
По-моему мнению -- нейминги надо изменить, т.к. они неочевидные. Мои предложения:
Событие в событие: `eventToEvent`
Событие в поток: `eventToStream`
Поток в поток: `streamToStream`

Получается такой вид трансформаций:
```kotlin
ButtonClicked1::class eventToEvent ::LoadData1,
ButtonClicked2::class eventToStream { loadData2() },
ButtonClicked3::class streamToStream { stream -> loadData3(stream) }
```

Более многословный, зато сходу понятный вариат. Для сокращения кол-ва символов можно создать extension-шорткаты примерно в таком виде:
```kotlin
ButtonClicked1::class etoe ::LoadData1,
ButtonClicked2::class etos { loadData2() },
ButtonClicked3::class stos { stream -> loadData3(stream) }
```

2022-02-20 15:02 UTC, ruslansharipov commented on docs/DSL.md
> +1. **mapTo** - трансформация события в событие. Используется, когда например событие клика по кнопке нужно трансформировать в событие открытие диалога.
По-моему крутая идея сделать названия более красноречивыми. Чтобы даже без чтения документации было понятно из одного названия трансформации что она делает.
@margarita-v что думаешь?

2022-02-21 14:02 UTC, margarita-v commented on docs/DSL.md
> +1. **mapTo** - трансформация события в событие. Используется, когда например событие клика по кнопке нужно трансформировать в событие открытие диалога.
Хорошее предложение, давайте так сделаем, но и в доке нужно будет прописать маппинги для нового ренейма, что и как теперь именуется

2022-03-01 11:58 UTC, margarita-v approved these changes

2022-03-01 11:58 UTC, margarita-v commented on README.md
> +[Документация на русском](docs/README.md)
```suggestion
[Russian docs](docs/README.md)
```

2022-03-01 11:58 UTC, margarita-v commented on docs/DSL.md
> +Названия некоторых транформаций в новой версии отличаются. Решено было изменить названия чтобы они были сходу понятны при чтении и вызывали меньше путаницы при использовании.
```suggestion
Названия некоторых транформаций в новой версии отличаются. Решено было изменить названия, чтобы они были сходу понятны при чтении и вызывали меньше путаницы при использовании.
```

2022-03-01 11:58 UTC, margarita-v commented on docs/DSL.md
> +1. **streamToStream** - трансформация потока событий в другой поток событий. Эта трансформация полезна, когда трансормации eventToEvent уже недостаточно и требуется модицицировать флоу событий исполь
```suggestion
1. **streamToStream** - трансформация потока событий в другой поток событий. Эта трансформация полезна, когда трансформации eventToEvent уже недостаточно и требуется модифицировать флоу событий, используя операторы реактивных цепочек. Например, filter, debounce, distinctUntilChanged и тд.   
```

2022-03-01 13:02 UTC, dmitry-kuzmenchuk requested changes

2022-03-01 13:02 UTC, dmitry-kuzmenchuk commented on docs/DSL.md
> +Для того, чтобы начать работать с DSL, необходимо унаследовать Middleware, использующийся в проекте, от [DslFlowMiddleware][DslFlowMiddleware], и переопределить метод `transform(eventStream)` следующ
Два раза написано [DslFlowMiddleware]

2022-03-01 13:19 UTC, dmitry-kuzmenchuk requested changes

2022-03-01 13:19 UTC, dmitry-kuzmenchuk commented on docs/DSL.md
> +            // Здесь будут перечислены возможные трансформации
Минорная идейка, как возможное улучшение QoL: 
можно было бы убрать один уровень вложенности в виде обязательного вызова метода addAll(...), если мы сделаем dsl-scope и переопределим в нем методы трансформации событий. Получилась бы такая запись:
```kotlin
eventStream.transformations {
    Navigation::class decomposeTo navigationMiddleware
    ButtonClicked::class eventToEvent ::ButtonClickedConfirmed
    ButtonClickedConfirmed::class eventToStream ::handleConfirmation
}
```

2022-03-01 13:19 UTC, dmitry-kuzmenchuk commented on docs/README.md
> +## Вычисление диффов при отрисовке состояния
Можно было бы еще упомянуть `DiffModerator`'ы, которые являются более продвинутыми и функциональными версиями `actionIfChanged`. Было бы неплохо вынести их как отдельную либу, которая хорошо дополняет наш mvi.
Название можно подобрать получше 😸

2022-03-01 13:21 UTC, dmitry-kuzmenchuk commented on docs/DSL.md
> +            // Здесь будут перечислены возможные трансформации
В рамках этого PRа никакие такие правки вносить точно не стоит, просто вкинул идею

2022-03-02 12:58 UTC, ruslansharipov commented on docs/README.md
> +## Вычисление диффов при отрисовке состояния
https://github.com/surfstudio/surf-mvi-flow/issues/12
создал Issue для доработки, хорошая идея вынести эту либу, точно не будет лишней

2022-03-02 13:19 UTC, ruslansharipov commented on docs/DSL.md
> +            // Здесь будут перечислены возможные трансформации
https://github.com/surfstudio/surf-mvi-flow/issues/13
добавил Issue

2022-03-02 13:25 UTC, dmitry-kuzmenchuk approved these changes

2022-03-02 16:05 UTC, merged