Compose
surfstudio/surf-mvi-flow pull request #15
Opened 2022-03-17 17:04 UTC by margarita-v

2022-03-17 18:10 UTC, ruslansharipov requested changes

2022-03-17 18:10 UTC, ruslansharipov commented on mvi-core/src/main/kotlin/ru/surfstudio/mvi/lifecycle/MviViewModel.kt
> +    val state by state.observeState().collectAsState(initial = initialState)
FlowState сейчас реализован так, что под капотом используется MutableStateFlow и при создании FlowState инициализируется с initialState. 
То есть стейт там уже будет в тот момент, когда мы попытаемся его извлечь. Поэтому можно переписать код и использовать этот стейт 
```kotlin
val state by state.observeState().collectAsState(initial = state.currentState)
```
и абстрактное поле initialState во вьюмодели можно убрать. Так как в большинстве случаев нет необходимости хранить начальный стейт экрана

2022-03-17 18:10 UTC, ruslansharipov commented on mvi-core/src/main/kotlin/ru/surfstudio/mvi/lifecycle/MviViewModel.kt
> +fun interface ComposedViewContext<E : Event> {
Предлагаю вынести этот интерфейс в другой файл и добавить ему док

2022-03-17 18:18 UTC, margarita-v commented on mvi-core/src/main/kotlin/ru/surfstudio/mvi/lifecycle/MviViewModel.kt
> +fun interface ComposedViewContext<E : Event> {
Я бы оставила тут, тк он вспомогательный и относится к renders, которые в свою очередь расширяет MviViewModel, доку добавила

2022-03-17 18:20 UTC, ruslansharipov approved these changes

2022-03-18 08:09 UTC, ArtJapp approved these changes

2022-03-18 08:25 UTC, merged